/* MetaStrip build: node build.mjs

   There is still no framework, no dependency and no transpiler. This does one
   thing: it concatenates the scripts in js/ into a single bundle, in the order
   the page loads them.

   The reason is not speed, though it is faster. Every file a visitor asks for
   is a billable edge request, and sixteen scripts meant a first visit cost
   about twenty requests before anyone had cleaned anything. A hobby plan gets
   a million a month, so that arithmetic decides how much traffic the site can
   absorb before it goes dark. One bundle takes a visit down to about five.

   The individual files stay the source of truth. They are what you edit, what
   the tests load, and what you read. The bundle is generated, committed so a
   plain static server still works with no build step, and checked by the test
   suite so it can never quietly drift from its sources. */

import fs from "node:fs";
import path from "node:path";

const ROOT = import.meta.dirname;
const JS_DIR = path.join(ROOT, "js");
const BUNDLE = path.join(JS_DIR, "bundle.js");

/* Load order matters. These are plain scripts sharing one global scope, so
   this list is the contract: motion first because it runs on its own, then
   the readers, then app.js which wires the page, then everything that reaches
   into the DOM app.js built. */
export const BUNDLE_ORDER = [
  "motion.js",
  "score.js",
  "aitags.js",
  "c2pa.js",
  "edits.js",
  "pdf.js",
  "audio.js",
  "exif.js",
  "video.js",
  "storage.js",
  "stripper.js",
  "app.js",
  "linkage.js",
  "receipt.js",
  "redact.js",
  "folder.js",
];

export function buildBundle(jsDir = JS_DIR) {
  const header = `/* MetaStrip bundle, generated by build.mjs. Do not edit.
   Sources are the files in js/, in this order:
   ${BUNDLE_ORDER.join(", ")} */\n`;

  const parts = BUNDLE_ORDER.map((name) => {
    const source = fs.readFileSync(path.join(jsDir, name), "utf8");
    return `\n/* ===== ${name} ===== */\n${source.trimEnd()}\n`;
  });

  return header + parts.join("");
}

/* Only writes when something changed, so a no-op build leaves the file's
   timestamp alone and git stays quiet. */
function main() {
  const next = buildBundle();
  const current = fs.existsSync(BUNDLE) ? fs.readFileSync(BUNDLE, "utf8") : null;
  if (current === next) {
    console.log(`bundle.js already current (${BUNDLE_ORDER.length} files, ${formatSize(next.length)})`);
    return;
  }
  fs.writeFileSync(BUNDLE, next);
  console.log(`wrote js/bundle.js from ${BUNDLE_ORDER.length} files, ${formatSize(next.length)}`);
}

function formatSize(bytes) {
  return bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

if (process.argv[1] && process.argv[1].endsWith("build.mjs")) main();
